apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-bfsy
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-bfsy
    app.kubernetes.io/part-of: integ-app-qzun
  name: hacbs-test-project-bfsy
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-bfsy
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-bfsy
    spec:
      containers:
      - image: quay.io/quay-or-not-to-quay/nbe-e2e-jsne-tenant/integ-app-qzun/hacbs-test-project-bfsy@sha256:9d89e22781f3c4e2ab80421836c9edaee2130b278cf981218f1332ec47a38e7d
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
